name: Phase4-SIP-Mock-Server

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Phase4-SIP-Mock-Server-NYPL
      run: docker build ./Phase4-SIP-Mock-Server -t Phase4-SIP-Mock-Server

